"""add receive_type to partner_receive_shipments

Revision ID: a39273ff51be
Revises: 881aeda2bc40
Create Date: 2026-08-05 16:32:40.788241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39273ff51be'
down_revision: Union[str, Sequence[str], None] = '881aeda2bc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_receive_shipments', sa.Column('receive_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_receive_shipments', 'receive_type')
    # ### end Alembic commands ###
