"""Add location to equipment

Revision ID: e6a2cbf631bd
Revises: 0df193fe22b2
Create Date: 2026-07-22 15:15:39.627621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a2cbf631bd'
down_revision: Union[str, Sequence[str], None] = '0df193fe22b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipments', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'location_id')
    # ### end Alembic commands ###
